FROM mongo:3

ENV sourcesdir /go/src/github.com/junior/mushop/src/user/
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN apt-get update && apt-get install -yq git curl

RUN curl -sSL https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz -o go.tar.gz && \
    tar -C /usr/local -xvf go.tar.gz
RUN go get -v github.com/Masterminds/glide

COPY . ${sourcesdir}
WORKDIR ${sourcesdir}
RUN glide install
