CREATE USER catalogue_user IDENTIFIED BY default_Password1;

GRANT DWROLE TO catalogue_user;


GRANT CREATE SESSION TO catalogue_user;

CREATE ROLE catalogue_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON products TO catalogue_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON categories TO catalogue_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON product_category TO catalogue_role;

GRANT UNLIMITED TABLESPACE TO catalogue_role;

GRANT catalogue_role TO catalogue_user;



CREATE TABLE products (
	sku VARCHAR2(20) NOT NULL, 
	brand VARCHAR2(20),
	title VARCHAR2(40), 
	description VARCHAR2(500), 
	weight VARCHAR2(10),
	product_size VARCHAR2(25),
	colors VARCHAR2(20),
	qty NUMBER(10, 0),
	price FLOAT, 
	image_url_1 VARCHAR2(50), 
	image_url_2 VARCHAR2(50), 
	PRIMARY KEY(sku)
);

CREATE TABLE categories (
	category_id NUMBER(7,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, 
	name VARCHAR2(30), 
	PRIMARY KEY(category_id)
);

CREATE TABLE product_category (
	sku VARCHAR2(40), 
	category_id NUMBER(7,0) NOT NULL, 
	FOREIGN KEY (sku) 
		REFERENCES products(sku), 
	FOREIGN KEY(category_id)
		REFERENCES categories(category_id)
);

INSERT INTO products VALUES ('MU-US-001', 'Original', 'Original Unscented Formula Cat Litter', 'Provide effective cat litter odor control in your cat','151lbs','0','0', 99, 18.50, '/catalogue/images/litter/01/01.jpg', '/catalogue/images/litter/01/02.jpg');
INSERT INTO products VALUES ('MU-US-002', 'Tidy Cats', 'Instant Action Litter for Multiple Cats', 'Put an end to overpowering odors in your home with Purina','20lbs','0','0', 99, 28.99 , '/catalogue/images/litter/02/01.jpg', '/catalogue/images/litter/02/02.jpg');
INSERT INTO products VALUES ('MU-US-003', 'Choco Spring', 'Cat Litter Deodorizer', 'With Choco Spring scents lingering in the air, your cat','26Oz','0','0', 99, 7.99, '/catalogue/images/litter/03/01.jpg', '/catalogue/images/litter/03/01.jpg');
INSERT INTO products VALUES ('MU-US-004', 'Arm & Hammer', 'Cat Litter Deodorizer Powder', 'Add an extra boost of freshness to your litter box. ARM','20Oz','0','0', 99, 4.99, '/catalogue/images/litter/04/01.jpg', '/catalogue/images/litter/04/01.jpg');
INSERT INTO products VALUES ('MU-US-005', 'Petmate', 'Cat Litter Pan With Rim', 'Stay Fresh litter pans are created with Microban ','0','18.7" x 15.5" x 10.6"','0', 99, 9.50, '/catalogue/images/litter/05/01.jpg', '/catalogue/images/litter/05/01.jpg');
INSERT INTO products VALUES ('MU-US-006', 'Tidy Cats', 'Tidy Cat Breeze Cat Litter System', 'Change the way you think about cleaning your cat','0','18.7" x 15.5" x 10.6"','0', 99, 39.25, '/catalogue/images/litter/06/01.jpg', '/catalogue/images/litter/06/02.jpg');
INSERT INTO products VALUES ('MU-US-007', 'Petsafe', 'Original Pet Fountain', 'Original Pet Fountain with Bonus Reservoir provides 50 oz','0','0','0', 99, 43.95, '/catalogue/images/feeders/07/01.jpg', '/catalogue/images/feeders/07/02.jpg');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');
INSERT INTO products VALUES ('SKU', 'BRAND', 'TITLE', 'DESC','WEIGHT','SIZE','0', 99, PRICE, '/catalogue/images/one', '/catalogue/images/two');





INSERT INTO categories (name) VALUES ('Cleaning Supplies');
INSERT INTO categories (name) VALUES ('Deodorizers');
INSERT INTO categories (name) VALUES ('Litter Accessories');
INSERT INTO categories (name) VALUES ('Litter Boxes');
INSERT INTO categories (name) VALUES ('Auto Feeders');
INSERT INTO categories (name) VALUES ('Bowls');
INSERT INTO categories (name) VALUES ('Placemats');
INSERT INTO categories (name) VALUES ('Storage');
INSERT INTO categories (name) VALUES ('Dry Food');
INSERT INTO categories (name) VALUES ('Food Pouches');
INSERT INTO categories (name) VALUES ('Limited Diet');
INSERT INTO categories (name) VALUES ('Wet Food');
INSERT INTO categories (name) VALUES ('Brushes');
INSERT INTO categories (name) VALUES ('Grooming Tools');
INSERT INTO categories (name) VALUES ('Shampoos and Conditioners');

INSERT INTO product_category VALUES ('MU-US-001', '3');
INSERT INTO product_category VALUES ('MU-US-002', '3');
INSERT INTO product_category VALUES ('MU-US-003', '2');
INSERT INTO product_category VALUES ('MU-US-004', '2');
INSERT INTO product_category VALUES ('MU-US-005', '4');
INSERT INTO product_category VALUES ('MU-US-006', '4');
INSERT INTO product_category VALUES ('MU-US-007', '5');




