#! /bin/sh

# This script prepares the OADB user schema statements by using
# env var subsitition for configured values of ${OADB_SCHEMA_USER}
# and ${OADB_SCHEMA_USER_PW}.

cat <<EOF
CREATE USER ${OADB_SCHEMA_USER} IDENTIFIED BY ${OADB_SCHEMA_USER_PW};

GRANT CREATE SESSION TO ${OADB_SCHEMA_USER};

GRANT UNLIMITED TABLESPACE TO ${OADB_SCHEMA_USER};

CREATE ROLE ${OADB_SCHEMA_USER}_role;

GRANT
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE SEQUENCE
TO ${OADB_SCHEMA_USER}_role;

GRANT ${OADB_SCHEMA_USER}_role TO ${OADB_SCHEMA_USER};

ALTER USER ${OADB_SCHEMA_USER} ACCOUNT UNLOCK;
EOF