ARG APPLICATION_NAME="fulfillment"
ARG VERSION="0.0.1-SNAPSHOT"

# Stage 1 : Setup the build environment
FROM gradle:6.5-jdk11 as buildenv

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY settings.gradle /usr/src/app
# copy buildscript and cache all dependencies
COPY build.gradle /usr/src/app
COPY gradle.properties /usr/src/app
#RUN gradle --refresh-dependencies

# Stage 2 : Build the application
FROM buildenv as appbuild
# Copy the source code.
# This layer is recreated only when there are actual source chnages
COPY src /usr/src/app/src
# build an executable fat jar
RUN gradle clean assemble

# Alternate build - using a JVM
FROM openjdk:11-jre-slim
# copy the generated application distribution
COPY --from=appbuild /usr/src/app/build/libs/fulfillment-*-all.jar /app/${APPLICATION_NAME}-${VERSION}.jar
EXPOSE 8099
WORKDIR /app
ENV APPLICATION_NAME=${APPLICATION_NAME}
ENV VERSION=${VERSION}
ENTRYPOINT java $JAVA_OPTS -jar /app/${APPLICATION_NAME}-${VERSION}.jar
